#! /usr/bin/env python
import sys
from pony_build_client import BuildCommand, TestCommand, do, send, \
     TempDirectoryContext, SetupCommand, GitClone, check
import os
import tempfile
import shutil

python_exe = sys.argv[1]
repo_url = 'git://github.com/ctb/pygr.git'

tags = [python_exe]
name = 'pygr'
server_url = 'http://localhost:8080/xmlrpc'
#server_url = 'http://lyorn.idyll.org/ctb/pb-dev/xmlrpc'

if not check(name, server_url, tags=tags):
    print 'check build says no need to build; bye'
    sys.exit(0)

context = TempDirectoryContext()
commands = [ GitClone(repo_url, name='checkout', cache_dir='/tmp/pygr'),
             BuildCommand([python_exe, 'setup.py', 'build_ext', '-i'],
                          name='compile', run_cwd='pygr'),
             TestCommand([python_exe, 'runtest.py', 'seqdb_test.py'],
                         name='run seqdb_test', run_cwd='pygr/tests')
             ]

results = do(name, commands, context=context)
send(server_url, results, tags=tags)
