#! /usr/bin/env python
import sys
from pony_build_client import BuildCommand, TestCommand, do, send, \
     TempDirectoryContext, SetupCommand
import os
import tempfile
import shutil

python_exe = sys.argv[1]
repo_url = sys.argv[2]

name = 'pygr.' + python_exe
server_url = 'http://localhost:8080/xmlrpc'
#server_url = 'http://lyorn.idyll.org/ctb/pb-dev/xmlrpc'

context = TempDirectoryContext()
commands = [ SetupCommand(['git', 'clone', repo_url],
                          name='checkout'),
             BuildCommand([python_exe, 'setup.py', 'build_ext', '-i'],
                          name='compile', run_cwd='pygr'),
             TestCommand([python_exe, 'runtest.py', 'seqdb_test.py'],
                         name='run seqdb_test', run_cwd='pygr/tests')
             ]

results = do(name, commands, context=context)
send(server_url, results, hostname='laptop')
