#! /usr/bin/env python
import sys
from pony_build_client import BuildCommand, TestCommand, do, send, check, \
     TempDirectoryContext

name = 'build-example'
server_url = 'http://localhost:8080/xmlrpc'

hostname = 'laptop'
arch = None
tags = ['tag1', 'tag2', 'tag3']

if not check(name, server_url, tags=tags, hostname=hostname, arch=arch):
    print 'check build says no need to build; bye'
    sys.exit(0)

commands = [ BuildCommand(['/bin/echo', 'hello, world'], name='David'),
             TestCommand(['/bin/echo', 'this is a test'], name='Bill')
             ]

context = TempDirectoryContext()
results = do(name, commands, context=context, stop_if_failure=False, arch=arch)
send(server_url, results, hostname=hostname, tags=tags)
