#! /usr/bin/env python
import sys
import pprint
from pony_client import BuildCommand, TestCommand, do, send, \
     TempDirectoryContext, SetupCommand, SvnUpdate, check, parse_cmdline

options, args = parse_cmdline()
if args:
    print 'ignoring command line args: ', args

repo_url = 'https://twill.googlecode.com/svn/branches/0.9.2-dev/twill'

python_exe = 'python2.5'
if args:
    python_exe = args[0]

name = 'twill'
tags = [python_exe]
server_url = options.server_url

if not options.force_build:
    if not check(name, server_url, tags=tags):
        print 'check build says no need to build; bye'
        sys.exit(0)

commands = [ SvnUpdate('twill', repo_url, name='checkout'),
             BuildCommand([python_exe, 'setup.py', 'test'])
             ]

context = TempDirectoryContext()
results = do(name, commands, context=context)
client_info, reslist, files = results

if options.report:
    print 'result: %s; sending' % (client_info['success'],)
    send(server_url, results, tags=tags)
else:
    print 'build result:'
    pprint.pprint(client_info)
    pprint.pprint(reslist)
    
    print '(NOT SENDING BUILD RESULT TO SERVER)'

if not client_info['success']:
    sys.exit(-1)
