#! /usr/bin/env python
from pony_build_client import BuildCommand, TestCommand, do

name = 'build-example'
server_url = 'http://localhost:8080/xmlrpc'

commands = [ BuildCommand(['/bin/echo', 'hello, world']),
             BuildCommand(['/bin/ls', '/blahblah']),
             TestCommand(['/bin/echo', 'this is a test'])
             ]

do(name, commands, server_url)
