#! /usr/bin/env python
import sys
from pony_client import BuildCommand, TestCommand, do, send, check, \
	TempDirectoryContext, SetupCommand, SvnCheckout,  parse_cmdline


options, args = parse_cmdline()
if args:
	print 'ignoring args: ', args

python_exe = 'python'
name = 'build-zope'
repo_url = 'http://svn.zope.org/repos/main/Zope/trunk/'
server_url = options.server_url

tags = ['zope']

if not options.force_build:
    if not check(name, server_url, tags=tags):
        print 'check build says no need to build; bye'
        sys.exit(0)

context = TempDirectoryContext()

commands = [ SvnCheckout('Zope', repo_url, name='checkout'),
	     BuildCommand(['python', 'setup.py', 'install']),
	     TestCommand([python_exe, 'src/Testing/tests/test_makerequest.py'], name='test')
 ]


results = do(name, commands, context=context, stop_if_failure=False)
client_info, reslist, files_to_upload = results
 
if options.report:
    print 'result: %s; sending' % (client_info['success'],)
    send(server_url, results, tags=tags)
else:
 
    print 'build result:'
 
    import pprint
    pprint.pprint(client_info)
    pprint.pprint(reslist)
    
    print '(NOT SENDING BUILD RESULT TO SERVER)'
 
if not client_info['success']:
    sys.exit(-1)
