#! /usr/bin/env python
from pony_build_client import BuildCommand, TestCommand, do, send

name = 'example'
server_url = 'http://localhost:8080/xmlrpc'

commands = [ BuildCommand(['/bin/echo', 'hello, world'], name='step 1'),
             TestCommand(['/bin/echo', 'this is a test'], name='step 2')
             ]

results = do('package name', commands)
send('http://localhost:8080/xmlrpc', results)
