#! /usr/bin/env python
import sys
from pony_build_client import BuildCommand, TestCommand, do, send, \
     TempDirectoryContext, SetupCommand, SvnClone, check
import os
import tempfile
import shutil

python_exe = sys.argv[1]
repo_url = 'http://twill.googlecode.com/svn/trunk/twill'

tags = [python_exe]
name = 'twill'
#server_url = 'http://localhost:8080/xmlrpc'
server_url = 'http://lyorn.idyll.org/ctb/pb-dev/xmlrpc'

if not check(name, server_url, tags=tags):
    print 'check build says no need to build; bye'
    sys.exit(0)

context = TempDirectoryContext(False)
commands = [ SvnClone('twill', repo_url, name='checkout', cache_dir='/u/t/.pony-build/twill'),
             BuildCommand([python_exe, 'setup.py', 'build'],
                          name='compile'),
             TestCommand(['nosetests'], name='run tests'),
             ]

results = do(name, commands, context=context)
send(server_url, results, tags=tags)
