#! /usr/bin/env python
import sys
import pprint
from pony_client import BuildCommand, TestCommand, do, send,_run_command, \
     Context, SetupCommand, HgClone, VirtualenvContext, check, parse_cmdline, \
     PythonPackageEgg

options, args = parse_cmdline()

python_exe = 'python'
if args:
    python_exe = args[0]

repo_url = 'http://hg.python.org/distutils2/'

tags = [python_exe]
name = 'distutils2'
server_url = options.server_url

if not options.force_build:
    if not check(name, server_url, tags=tags):
        print 'check build says no need to build; bye'
        sys.exit(0)


context = VirtualenvContext(dependencies=['unittest2'], python=python_exe)

commands = [ HgClone(repo_url, name='checkout'),
             TestCommand([python_exe, 'runtests.py', 'test'], name='run tests',
                         run_cwd='src') ]

results = do(name, commands, context=context)
client_info, reslist, files = results
if options.report:
    print 'result: %s; sending' % (client_info['success'],)
    send(server_url, results, tags=tags)
else:
    print 'build result:'
    pprint.pprint(client_info)
    pprint.pprint(reslist)

    print '(NOT SENDING BUILD RESULT TO SERVER)'

if not client_info['success']:
    sys.exit(-1)
