#! /usr/bin/env python
import sys
import pprint
import distutils
from pony_client import BuildCommand, TestCommand, do, send, \
     TempDirectoryContext, SetupCommand, SvnCheckout, check, parse_cmdline

options, args = parse_cmdline()
if args:
    print 'ignoring command line args: ', args
    
###

repo_url = 'http://svn.python.org/projects/python/branches/py3k'

tags = ['py3k']
name = 'python'

server_url = options.server_url

if not options.force_build:
    if not check(name, server_url, tags=tags):
        print 'check build says no need to build; bye'
        sys.exit(0)

# correct for Mac OS X python build
built_exe = './python'
if distutils.util.get_platform().startswith('macosx'):
    built_exe = './python.exe'

context = TempDirectoryContext()
commands = [ SvnCheckout('python32', repo_url, name='checkout'),
             BuildCommand(['./configure'], name='configure'),
             BuildCommand(['make'], name='make'),
             TestCommand([built_exe, 'Lib/test/regrtest.py'], name='regrtest')
             ]

results = do(name, commands, context=context)
client_info, reslist, files = results

if options.report:
    print 'result: %s; sending' % (client_info['success'],)
    send(server_url, results, tags=tags)
else:
    
    print 'build result:'
    pprint.pprint(client_info)
    pprint.pprint(reslist)

if not client_info['success']:
    sys.exit(-1)
