#! /usr/bin/env python
import sys
from pony_build_client import BuildCommand, TestCommand, do, send, \
     TempDirectoryContext, SetupCommand, SvnClone, check
import os
import tempfile
import shutil

repo_url = 'http://svn.python.org/projects/python/trunk'

tags = ['python2.7']
name = 'python'
#server_url = 'http://localhost:8080/xmlrpc'
server_url = 'http://lyorn.idyll.org/ctb/pb-dev/xmlrpc'

if not check(name, server_url, tags=tags) and 0:
    print 'check build says no need to build; bye'
    sys.exit(0)

context = TempDirectoryContext(False)
commands = [ SvnClone('python27', repo_url, name='checkout', cache_dir='/u/t/.pony-build/python27'),
             BuildCommand(['configure'], name='configure'),
             BuildCommand(['make'], name='make'),
             TestCommand(['./python', 'Lib/test/regrtest.py'], name='regrtest')
             ]

results = do(name, commands, context=context)
send(server_url, results, tags=tags)
