#! /usr/bin/env python
import sys
import distutils
from pony_client import BuildCommand, TestCommand, do, send, \
     Context, TempDirectoryContext, SetupCommand, SvnCheckout, check, parse_cmdline

options, args = parse_cmdline()
if args:
    print 'ignoring command line args: ', args

###

repo_url = 'http://svn.python.org/projects/python/trunk'

tags = ['python2.7']
name = 'python'

server_url = options.server_url

if not options.force_build:
    if not check(name, server_url, tags=tags):
        print 'check build says no need to build; bye'
        sys.exit(0)


context = Context()
#SvnCheckout('python27', repo_url, name='checkout', cache_dir='~/.pony-build/python27'),

commands = [
             BuildCommand(['build.bat'], name='build.bat', run_cwd='pcbuild', subprocess_kwargs=dict(shell=True), ignore_failure=True, verbose=True),
             TestCommand(['pcbuild\\python.exe', 'Lib\\test\\regrtest.py', '-x', 'test_ttk_textonly', 'test_bz2', 'test_ttk_guionly', 'test_bsddb', 'test_ssl', 'test_tcl', 'test_tk', 'test_readline', 'test_sqlite', 'test_distutils', 'test_winsound'], name='regrtest')
             ]

results = do(name, commands, context=context)
client_info, reslist, files = results

if options.report:
    print 'result: %s; sending' % (client_info['success'],)
    send(server_url, results, tags=tags)
else:

    print 'build result:'

    import pprint
    pprint.pprint(client_info)
    pprint.pprint(reslist)

if not client_info['success']:
    sys.exit(-1)
