#! /usr/bin/env python
import sys
from pony_client import BuildCommand, TestCommand, do, send, \
     VirtualenvContext, SetupCommand, GitClone, check, parse_cmdline
     
import os
import tempfile
import shutil
import pprint

options, args = parse_cmdline()

python_exe = 'python'
if args:
    python_exe = args[0]

name = 'build-pb-env'
repo_url = 'git://github.com/ctb/pony-build.git'
server_url = options.server_url
tags = ['pb', 'env']

context = VirtualenvContext(dependencies=['Jinja2', 'Quixote', 'twill','nose'],
                            python=python_exe)

commands = [ GitClone(repo_url, name='checkout'),            
             BuildCommand(['python', 'setup.py', 'install'], name='install'),
             BuildCommand(['python', '-m', 'pony_build.tests.run']) 
]


results = do(name, commands, context=context, stop_if_failure=False)
client_info, reslist, files_to_upload = results

if options.report:
    print 'result: %s; sending' % (client_info['success'],)
    send(server_url, results, tags=tags)
else:

    print 'build result:'

    import pprint
    pprint.pprint(client_info)
    pprint.pprint(reslist)

    print '(NOT SENDING BUILD RESULT TO SERVER)'

if not client_info['success']:
    sys.exit(-1)

