#! /usr/bin/env python
import sys
import pprint
from pony_client import BuildCommand, TestCommand, do, send,_run_command, \
     TempDirectoryContext, Context, SetupCommand, SvnCheckout, VirtualenvContext, check, parse_cmdline, \
     PythonPackageEgg

options, args = parse_cmdline()

python_exe = 'python'
if args:
    python_exe = args[0]

repo_url = 'http://mock.googlecode.com/svn/trunk/'
dirname = 'mock-read-only'
tags = [python_exe]
name = 'mock'
server_url = options.server_url

if not options.force_build:
    if not check(name, server_url, tags=tags):
        print 'check build says no need to build; bye'
        sys.exit(0)


context = TempDirectoryContext()
commands = [ SvnCheckout(dirname, repo_url, name='checkout'),
             BuildCommand([python_exe, 'setup.py', 'build_ext', '-i'],
                          name='compile'),
             TestCommand([python_exe, 'discover.py'], name='run tests'),
             PythonPackageEgg(python_exe)]

results = do(name, commands, context=context)
client_info, reslist, files = results
if options.report:
    print 'result: %s; sending' % (client_info['success'],)
    send(server_url, results, tags=tags)
else:
    print 'build result:'
    pprint.pprint(client_info)
    pprint.pprint(reslist)

    print '(NOT SENDING BUILD RESULT TO SERVER)'

if not client_info['success']:
    sys.exit(-1)
