#! /usr/bin/env python
import sys
import os
import shutil
from pony_client import HgClone, Context, TempDirectoryContext, _run_command

context = Context()

url = 'http://bitbucket.org/ctb/pony-build-hg-test/'

# first, set up a simple hg repository
shutil.rmtree('pony-build-hg-test')
(ret, out, err) = _run_command(['hg', 'clone', url])
assert ret == 0, (out, err)

# check out revision 0
(ret, out, err) = _run_command(['hg', 'checkout', '0'],
                               cwd='pony-build-hg-test')
assert ret == 0, (out, err)
assert os.path.exists(os.path.join('pony-build-hg-test', 'test1'))
assert not os.path.exists(os.path.join('pony-build-hg-test', 'test2'))

# now, run the HgClone command and verify that it Does the Right Thing
command = HgClone(url)
command.run(context)
print command.get_results()

# check to make sure the right files are there
assert os.path.exists(os.path.join('pony-build-hg-test', 'test1'))
assert os.path.exists(os.path.join('pony-build-hg-test', 'test2'))

##
shutil.rmtree('pony-build-hg-test')
