#! /usr/bin/env python
import sys, os
import tempfile

import pony_client

# set up a temp directory to test the cache dir stuff
cache_loc = tempfile.mkdtemp()
print 'using temp dir for cache:', cache_loc

os.environ['PONY_BUILD_CACHE'] = cache_loc

# set up another temp dir to do the checkout
testdir = tempfile.mkdtemp()
print 'using temp dir for testing:', testdir

os.chdir(testdir)

context = pony_client.Context()
clone = pony_client.GitClone('git://github.com/ctb/pony-build.git')

context.initialize()
context.start_command(clone)
clone.run(context)
context.end_command(clone)

print 'success or failure?', clone.success()

# we should see that in the putative cache dir, pony-build/README.txt exists.
testfile = os.path.join(cache_loc, 'pony-build', 'README.txt')
print '** cache dir created?', os.path.exists(testfile)
print testfile, 'exists'

# we should also see that in the final checkout dir, pony-build/README.txt is
# there.
testfile = os.path.join(testdir, 'pony-build', 'README.txt')
print '** final checkout success?', os.path.exists(testfile)
print testfile, 'exists'
